#---------------------------
# Hexo Theme Miracle
# Author: HiFun Team
# GitHub: https://github.com/hifun-team/hexo-theme-miracle
#---------------------------

#---------------------------
# 全局
# Global
#---------------------------

global:

    # 浏览器标签页中的标题分隔符，效果： 文章名 - 站点名
    # Title separator in browser tab, eg: article - site
    title_join_string: " - "

    # 页脚文字（支持 HTML 格式）
    # Footer text (supports HTML)
    footer:
        cotent: ''
    
    # 主题字体设置
    # Theme font settings
    font:
        family: "'Noto Sans SC', sans-serif"
        css: 

    # 每次生成页面后，检测主题是否为最新版本
    # Every time the page is generated, detect whether the theme is the latest version
    version_check: true # 主题版本相关

#---------------------------
# 主页
# Homepage
#---------------------------
index:
    # Banner Slogan
    # 输出在 Banner 标题下方的文字
    # The text below banner title
    banner_slogan: Write the miracle in your heart.

    # 为 Slogan 添加打字机效果
    # Typing animation for slogan
    slogan_typing:
        enable: true

        # 打印速度，数字越大越慢
        # Typing speed, the larger the number, the slower
        typeSpeed: 55

        # 游标字符
        # Cursor character
        cursorChar: "|"

    # 文章通过 sticky 排序后，在首页文章标题前显示图标
    # If the posts are sorted by `sticky`, an icon is displayed in front of the post title
    post_sticky:
        enable: true
        icon: "fa fa-thumb-tack"

    # 文章卡片是否显示相关信息（时间、分类、标签）
    # Whether the article card displays relevant information (time, category, label)
    post_meta:
        date: true
        category: true
        tag: true

    # 自动截取文章摘要
    # Auto extract post
    auto_excerpt:
        enable: true

navbar:
    # 模糊像素，只能为数字，数字越大模糊度越高
    # Number of blurred pixel. the larger the number, the higher the blur
    blur: 3

    # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
    # Navigation bar menu. `key` is used to associate languages/*.yml. If there is no association, the value of `key` itself will be displayed; if `icon` is a css class, it can be omitted; adding `name` can force the display of the specified name
    menu:
        - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
        - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
        - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
        - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
        # - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }
        - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }


#---------------------------
# 以下是配置 JS CSS 静态资源的 URL 前缀，可以自定义成 CDN 地址，
# 如果需要修改，最好使用与默认配置相同的版本，以避免潜在的问题，
# 在站点上启用 HTTPS 时，请使用 CDN 地址的 HTTPS 协议，
# ** 如果你不知道如何设置，请不要做任何改动 **
#
# Here is the url prefix to configure JS and CSS static assets. Set CDN addresses you want to customize.
# Be aware that you would better use the same version as default ones to avoid potential problems.
# Use the HTTPS protocol of CDN url when you enable HTTPS on your site.
# DO NOT EDIT THE FOLLOWING SETTINGS UNLESS YOU KNOW WHAT YOU ARE DOING
#---------------------------

static_prefix:

    font: https://fonts.googleapis.com/css2?family=Noto+Sans+SC&display=swap
    jquery: https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/
    typed: https://cdn.jsdelivr.net/npm/typed.js@2.0.11/lib/