#---------------------------
# Hexo Theme Miracle
# Author: HiFun Team
# GitHub: https://github.com/hifun-team/hexo-theme-miracle
#---------------------------

#---------------------------
# 全局
# Global
#---------------------------

global:
    # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
    # The title on the left side of the navigation bar. If empty, it is based on `title` in hexo config
    nav_title: Miracle

    # 浏览器标签页中的标题分隔符，效果： 文章名 - 站点名
    # Title separator in browser tab, eg: article - site
    title_join_string: " - "

    # 页脚文字（支持 HTML 格式）
    # Footer text (supports HTML)
    footer:
        cotent: ''
    
    # 主题字体设置
    # Theme font settings
    font:
        family: "'Noto Sans SC', sans-serif"
        css: 

    # 每次生成页面后，检测主题是否为最新版本
    # Every time the page is generated, detect whether the theme is the latest version
    version_check: true # 主题版本相关

    # 为 Banner 标题 添加打字机效果
    # Typing animation for banner header
    typing:

        enable: true

        # 打印速度，数字越大越慢
        # Typing speed, the larger the number, the slower
        typeSpeed: 55

        # 游标字符
        # Cursor character
        cursorChar: "|"

    web_analytics:

        

menu:
    Home: /
    Archives: /archives
    # Categories: /categories
    # Tags: /tags
    # Links: /links
    # About: /about
    # ...


#---------------------------
# 主页
# Homepage
#---------------------------
index:
    # Banner Slogan
    banner_slogan: Write the miracle in your heart.

    # 文章通过 `sticky` 排序后，在首页文章标题前显示图标
    # If the posts are sorted by `sticky`, an icon is displayed in front of the post title
    post_sticky:
        enable: true
        icon: "fa fa-thumb-tack"

    # 文章卡片是否显示相关信息（时间、分类、标签）
    # Whether the article card displays relevant information (time, category, label)
    post_meta:
        date: true
        category: true
        tag: true

    # 自动截取文章摘要
    # Auto extract post
    auto_excerpt:
        enable: true

navbar:
    # 模糊像素，只能为数字，数字越大模糊度越高
    # Number of blurred pixel. the larger the number, the higher the blur
    blur: 3

    # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
    # Navigation bar menu. `key` is used to associate languages/*.yml. If there is no association, the value of `key` itself will be displayed; if `icon` is a css class, it can be omitted; adding `name` can force the display of the specified name
    menu:
        - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
        - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
        - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
        - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
        # - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }
        - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

#---------------------------
# 文章页
# Post Page
#---------------------------
post:
    meta:
        # 作者，优先根据 `front-matter` 里 `author` 字段，其次是 `hexo` 配置中 `author` 值
        # Author, based on `author` field in front-matter, if not set, based on `author` value in hexo config
        author: true

        # 文章日期，优先根据 `front-matter` 里 date 字段，其次是 .md 文件日期
        # Post date, based on `date` field in front-matter, if not set, based on create date of .md file
        date: true

        # 格式参照 ISO-8601 日期格式化
        # ISO-8601 date format
        # See: http://momentjs.cn/docs/#/parsing/string-format/
        date_format: "LL"
    
    # 字数统计
    # Word count
    # 需要先安装 `hexo-wordcount` 插件
    # You need to install the `hexo wordcount` plugin first
    wordcount:
        enable: true

        # 所显示的文本，{} 是数字的占位符（必须包含）
        # Displayed text, {} is a placeholder for numbers (must be included)
        format: "共 {} 字"

    # 估计阅读全文需要的时长
    # Estimate the time required to read the full text
    # 需要先安装 `hexo-wordcount` 插件
    # You need to install the `hexo wordcount` plugin first
    min2read:
        enable: true
        format: "预计 {} 分钟"
        # 每分钟阅读多少字，如果是技术文章，建议降低
        # Words read per minute
        words: 120

    # 评论插件
    # Comment plugin
    comment: true
    
#---------------------------
# 评论插件
# Comment plugins
#
# 开启评论需要先设置上方 `post: comment: true`，然后根据 `type` 设置下方对应的评论插件参数
# Enable comments need to be set `post: comments: enable: true`, then set the corresponding comment plugin parameters below according to `type`
#---------------------------
comment:

    # 指定的插件，需要同时设置对应插件的必要参数
    # The specified plugin needs to set the necessary parameters at the same time
    # Options: gitalk | valine
    type: valine

    # Gitalk
    # 基于 GitHub Issues
    # Based on GitHub Issues
    # See: https://github.com/gitalk/gitalk#options

    gitalk:
        clientID: 
        clientSecret: 
        repo: 
        owner: 
        admin: ['name']
        language: zh-CN
        labels: ['Gitalk']
        perPage: 10
        pagerDirection: last
        distractionFreeMode: false
        createIssueManually: true

    valine:
        appid: 
        appkey: 
        placeholder:
        path: window.location.pathname
        avatar: mp
        meta: ['nick','mail','link']
        pageSize: 10
        lang: zh-CN
        highlight: true
        avatarForce: false
        recordIP: true
        serverURLs: 
        enableQQ: false
        requiredFields: ['nick','mail']






#---------------------------
# 以下是配置 JS CSS 静态资源的 URL 前缀，可以自定义成 CDN 地址，
# 如果需要修改，最好使用与默认配置相同的版本，以避免潜在的问题，
# 在站点上启用 HTTPS 时，请使用 CDN 地址的 HTTPS 协议，
# ** 如果你不知道如何设置，请不要做任何改动 **
#
# Here is the url prefix to configure JS and CSS static assets. Set CDN addresses you want to customize.
# Be aware that you would better use the same version as default ones to avoid potential problems.
# Use the HTTPS protocol of CDN url when you enable HTTPS on your site.
# DO NOT EDIT THE FOLLOWING SETTINGS UNLESS YOU KNOW WHAT YOU ARE DOING
#---------------------------

static_prefix:

    font: https://fonts.googleapis.com/css2?family=Noto+Sans+SC&display=swap
    jquery: https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/
    typed: https://cdn.jsdelivr.net/npm/typed.js@2.0.11/lib/
    gitalk: https://cdn.jsdelivr.net/npm/gitalk@1/dist/
    md5: https://cdn.jsdelivr.net/npm/blueimp-md5@2.18.0/js/
    valine: https://cdn.jsdelivr.net/npm/valine@1.4.14/dist/