name: Compress CSS

on:
  push:
    branches:
      - master
  
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Stylus
        run: |
          npm install stylus -g

      - name: Compress CSS
        run: |
          stylus source/css/main.styl -o source/css/main.min.css --compress
      
      - name: Push to repository
        run: |
          git config --global user.name "YFun Bot"
          git config --global user.email "awa@outlook.ie"
          export TZ='Asia/Shanghai'
          git add .
          git commit -m ":art: 压缩 CSS 代码"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin master
